/**
 * Last-resort embed URLs for when live mlbwebcast scrape fails (Vercel 403).
 * Refreshed 2026-09-12 from /stream/{slug}2.html — these remap often.
 * Prefer live scrape in /api/stream/embed; do not treat this map as truth.
 */
export const STREAM_IFRAME_FALLBACKS: Record<string, string> = {
  diamondbacks2: "https://streame.center/embed/ch28.php",
  diamondbacks3: "https://streame.center/embed/ch28.php",
  athletics2: "https://streame.center/embed/ch27.php",
  athletics3: "https://streame.center/embed/ch27.php",
  braves2: "https://streame.center/embed/ch26.php",
  braves3: "https://streame.center/embed/ch26.php",
  orioles2: "https://streame.center/embed/ch18.php",
  orioles3: "https://streame.center/embed/ch18.php",
  redsox2: "https://streame.center/embed/ch21.php",
  redsox3: "https://streame.center/embed/ch21.php",
  cubs2: "https://streame.center/embed/ch17.php",
  cubs3: "https://streame.center/embed/ch17.php",
  whitesox2: "https://streame.center/embed/ch27.php",
  whitesox3: "https://streame.center/embed/ch27.php",
  reds2: "https://streame.center/embed/ch25.php",
  reds3: "https://streame.center/embed/ch25.php",
  guardians2: "https://streame.center/embed/ch23.php",
  guardians3: "https://streame.center/embed/ch23.php",
  rockies2: "https://streame.center/embed/ch16.php",
  rockies3: "https://streame.center/embed/ch16.php",
  tigers2: "https://streame.center/embed/ch16.php",
  tigers3: "https://streame.center/embed/ch16.php",
  astros2: "https://streame.center/embed/ch24.php",
  astros3: "https://streame.center/embed/ch24.php",
  royals2: "https://streame.center/embed/ch21.php",
  royals3: "https://streame.center/embed/ch21.php",
  angels2: "https://streame.center/embed/ch18.php",
  angels3: "https://streame.center/embed/ch18.php",
  dodgers2: "https://streame.center/embed/ch22.php",
  dodgers3: "https://streame.center/embed/ch22.php",
  marlins2: "https://streame.center/embed/ch22.php",
  marlins3: "https://streame.center/embed/ch22.php",
  brewers2: "https://streame.center/embed/ch25.php",
  brewers3: "https://streame.center/embed/ch25.php",
  twins2: "https://streame.center/embed/ch23.php",
  twins3: "https://streame.center/embed/ch23.php",
  mets2: "https://streame.center/embed/ch16.php",
  mets3: "https://streame.center/embed/ch16.php",
  yankees2: "https://streame.center/embed/ch16.php",
  yankees3: "https://streame.center/embed/ch16.php",
  phillies2: "https://streame.center/embed/ch26.php",
  phillies3: "https://streame.center/embed/ch26.php",
  pirates2: "https://streame.center/embed/ch17.php",
  pirates3: "https://streame.center/embed/ch17.php",
  padres2: "https://streame.center/embed/ch20.php",
  padres3: "https://streame.center/embed/ch20.php",
  giants2: "https://streame.center/embed/ch20.php",
  giants3: "https://streame.center/embed/ch20.php",
  mariners2: "https://streame.center/embed/ch27.php",
  mariners3: "https://streame.center/embed/ch27.php",
  cardinals2: "https://streame.center/embed/ch27.php",
  cardinals3: "https://streame.center/embed/ch27.php",
  rays2: "https://streame.center/embed/ch24.php",
  rays3: "https://streame.center/embed/ch24.php",
  rangers2: "https://streame.center/embed/ch28.php",
  rangers3: "https://streame.center/embed/ch28.php",
  jays2: "https://streame.center/embed/ch18.php",
  jays3: "https://streame.center/embed/ch18.php",
  nationals2: "https://streame.center/embed/ch18.php",
  nationals3: "https://streame.center/embed/ch18.php",
  mlbnetwork2: "https://embedstreams.top/embed/alpha/mlb-network/1",
  mlbnetwork3: "https://embedstreams.top/embed/alpha/mlb-network/1"
};

export function iframeFallbackForSlug(slug: string): string | null {
  const key = slug.toLowerCase();
  return STREAM_IFRAME_FALLBACKS[key] ?? STREAM_IFRAME_FALLBACKS[`${key.replace(/\d+$/, "")}2`] ?? null;
}
