/**
 * Static fallback embed URLs for MLB Webcast numbered feeds.
 * Used when the live scrape of mlbwebcast.com is blocked (Cloudflare on Vercel).
 * Refresh periodically by re-reading /stream/{slug}.html iframe src.
 */
export const STREAM_IFRAME_FALLBACKS: Record<string, string> = {
  diamondbacks2: "https://streame.center/embed/ch22.php",
  diamondbacks3: "https://streame.center/embed/ch22.php",
  athletics2: "https://streame.center/embed/ch29.php",
  athletics3: "https://streame.center/embed/ch29.php",
  braves2: "https://streame.center/embed/ch24.php",
  braves3: "https://streame.center/embed/ch24.php",
  orioles2: "https://streame.center/embed/ch20.php",
  orioles3: "https://streame.center/embed/ch20.php",
  redsox2: "https://streame.center/embed/ch27.php",
  redsox3: "https://streame.center/embed/ch27.php",
  cubs2: "https://streame.center/embed/ch23.php",
  cubs3: "https://streame.center/embed/ch23.php",
  whitesox2: "https://streame.center/embed/ch16.php",
  whitesox3: "https://streame.center/embed/ch16.php",
  reds2: "https://streame.center/embed/ch19.php",
  reds3: "https://streame.center/embed/ch19.php",
  guardians2: "https://streame.center/embed/ch22.php",
  guardians3: "https://streame.center/embed/ch22.php",
  rockies2: "https://streame.center/embed/ch25.php",
  rockies3: "https://streame.center/embed/ch25.php",
  tigers2: "https://streame.center/embed/ch29.php",
  tigers3: "https://streame.center/embed/ch29.php",
  astros2: "https://streame.center/embed/ch21.php",
  astros3: "https://streame.center/embed/ch21.php",
  royals2: "https://streame.center/embed/ch25.php",
  royals3: "https://streame.center/embed/ch25.php",
  angels2: "https://streame.center/embed/ch28.php",
  angels3: "https://streame.center/embed/ch28.php",
  dodgers2: "https://streame.center/embed/ch27.php",
  dodgers3: "https://streame.center/embed/ch27.php",
  marlins2: "https://streame.center/embed/ch17.php",
  marlins3: "https://streame.center/embed/ch17.php",
  brewers2: "https://streame.center/embed/ch28.php",
  brewers3: "https://streame.center/embed/ch28.php",
  twins2: "https://streame.center/embed/ch18.php",
  twins3: "https://streame.center/embed/ch18.php",
  mets2: "https://streame.center/embed/ch17.php",
  mets3: "https://streame.center/embed/ch17.php",
  yankees2: "https://streame.center/embed/ch23.php",
  yankees3: "https://streame.center/embed/ch23.php",
  phillies2: "https://streame.center/embed/ch20.php",
  phillies3: "https://streame.center/embed/ch20.php",
  pirates2: "https://streame.center/embed/ch19.php",
  pirates3: "https://streame.center/embed/ch19.php",
  padres2: "https://streame.center/embed/ch26.php",
  padres3: "https://streame.center/embed/ch26.php",
  giants2: "https://streame.center/embed/ch26.php",
  giants3: "https://streame.center/embed/ch26.php",
  mariners2: "https://streame.center/embed/ch18.php",
  mariners3: "https://streame.center/embed/ch18.php",
  cardinals2: "https://streame.center/embed/ch15.php",
  cardinals3: "https://streame.center/embed/ch15.php",
  rays2: "https://streame.center/embed/ch16.php",
  rays3: "https://streame.center/embed/ch16.php",
  rangers2: "https://streame.center/embed/ch21.php",
  rangers3: "https://streame.center/embed/ch21.php",
  jays2: "https://streame.center/embed/ch15.php",
  jays3: "https://streame.center/embed/ch15.php",
  nationals2: "https://streame.center/embed/ch24.php",
  nationals3: "https://streame.center/embed/ch24.php",
  mlbnetwork2: "https://embedstreams.top/embed/alpha/mlb-network/1",
  mlbnetwork3: "https://embedstreams.top/embed/alpha/mlb-network/1",
};

export function iframeFallbackForSlug(slug: string): string | null {
  return STREAM_IFRAME_FALLBACKS[slug.toLowerCase()] ?? null;
}
